name: ALCO
version: "0.1"
license: "GPL-3.0-or-later"
date: 2024-01-15
description: |
    Tools for algebraic combinatorics

authors:
    - name: Benjamin Nasmith
      url: https://github.com/BNasmith/

maintainers:
    - name: Benjamin Nasmith
      url: https://github.com/BNasmith/

GAP: "4.12"

www: https://github.com/BNasmith/alco
readme: README.md
packageinfo: https://github.com/BNasmith/alco/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/BNasmith/alco/releases/download/v0.1/ALCO-0.1.tar.gz

abstract: |
    The <span class="pkgname">ALCO</span> package provides tools for algebraic combinatorics including implementations of octonion and Jordan algebras.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Octonions, Jordan algebras, t-Designs.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Nas24</span>]   <b class='BibAuthor'>Nasmith, B.</b>,
     <i class='BibTitle'>ALCO, Tools for algebraic combinatorics,
             Version 0.1</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/BNasmith/alco">https://github.com/BNasmith/alco</a></span>.
    </p>
    

bibtex: |
    @misc{ ALCO0.1,
      author =           {Nasmith, B.},
      title =            {{ALCO}, Tools for algebraic combinatorics, {V}ersion 0.1},
      month =            {Jan},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href                      {https://github.com/BNasmith/alco}
                          {\texttt{https://github.com/}\discretionary
                          {}{}{}\texttt{BNasmith/}\discretionary {}{}{}\texttt{alco}}},
      keywords =         {Octonions; Jordan algebras; t-Designs},
      printedkey =       {Nas24}
    }

