name: ALCO
version: "1.1.2"
license: "GPL-3.0-or-later"
date: 2025-09-05
description: |
    Tools for algebraic combinatorics

authors:
    - name: Benjamin Nasmith
      url: https://github.com/BNasmith/

maintainers:
    - name: Benjamin Nasmith
      url: https://github.com/BNasmith/

GAP: "4.14"

needed-pkgs:
    - name: "ResClasses"
      version: ">=4.7.3"
      url: "https://gap-packages.github.io/resclasses/"

www: https://bnasmith.github.io/alco/
readme: README.md
packageinfo: https://bnasmith.github.io/alco//PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/BNasmith/alco/releases/download/v1.1.2/ALCO-1.1.2.tar.gz

abstract: |
    The <span class="pkgname">ALCO</span> package provides tools for algebraic combinatorics including implementations of octonion and Jordan algebras.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Octonions, Jordan algebras, t-Designs.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Nas25</span>]   <b class='BibAuthor'>Nasmith, B.</b>,
     <i class='BibTitle'>ALCO, Tools for algebraic combinatorics,
             Version 1.1.2</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://bnasmith.github.io/alco/">https://bnasmith.github.io/alco/</a></span>.
    </p>
    

bibtex: |
    @misc{ ALCO,
      author =           {Nasmith, B.},
      title =            {{ALCO}, {Tools for algebraic combinatorics}, {V}ersion
                          1.1.2},
      month =            {Sep},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href               {https://bnasmith.github.io/alco/}
                          {\texttt{https://bnasmith.github.io/}\discretionary
                          {}{}{}\texttt{alco/}}},
      keywords =         {Octonions;               Jordan              algebras;
                          t\texttt{\symbol{45}}Designs},
      printedkey =       {Nas25}
    }

